#!/bin/bash
wget https://homes.cs.washington.edu/~jheer/files/zoo/index.png -O img/index.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/stacked_graph.png -O img/stacked_graph.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/small_multiples.png -O img/small_multiples.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/horizon.png -O img/horizon.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/stem_and_leaf_plot.png -O img/stem_and_leaf_plot.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/qq_plot.png -O img/qq_plot.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/scatter_plot.png -O img/scatter_plot.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/parallel.png -O img/parallel.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/napoleon.png -O img/napoleon.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/choropleth.png -O img/choropleth.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/graduated_symbol.png -O img/graduated_symbol.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/dorling.png -O img/dorling.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/tree.png -O img/ex-hierarchies-tree.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/cluster-radial.png -O img/ex-hierarchies-cluster-radial.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/indent.png -O img/ex-hierarchies-indent.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/icicle.png -O img/ex-hierarchies-icicle.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/sunburst.png -O img/ex-hierarchies-sunburst.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/treemap.png -O img/ex-hierarchies-treemap.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/hierarchies/pack.png -O img/ex-hierarchies-pack.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/networks/force.png -O img/ex-networks-force.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/networks/arc.png -O img/ex-networks-arc.png
wget https://homes.cs.washington.edu/~jheer/files/zoo/ex/networks/matrix.png -O img/ex-networks-matrix.png